apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: kennygt51-company
  description: The kennygt51 technical unit
spec:
  type: business-unit
  profile:
    displayName: kennygt51-tech
    email: kennygt51-tech@example.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gotokenn
spec:
  profile:
    displayName: gotokenn
    email: gootkenn@mamezou.com
  memberOf: [kennygt51-tech]